# Generated by Django 3.0.7 on 2020-07-06 03:40

from django.db import migrations, models
import hrm_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('first_name', models.CharField(max_length=25, validators=[hrm_api.models.first_name_validator])),
                ('last_name', models.CharField(max_length=25, validators=[hrm_api.models.last_name_validator])),
                ('email', models.EmailField(max_length=25, unique=True, validators=[hrm_api.models.email_validator])),
                ('password', models.CharField(max_length=100, validators=[hrm_api.models.password_validator])),
                ('gender', models.CharField(max_length=6, validators=[hrm_api.models.gender_validator])),
                ('birth_date', models.DateField(blank=True, null=True, validators=[hrm_api.models.birth_date_validator])),
                ('street_address', models.CharField(max_length=50, validators=[hrm_api.models.street_address_validator])),
                ('city', models.CharField(max_length=25, validators=[hrm_api.models.city_validator])),
                ('state', models.CharField(max_length=2, validators=[hrm_api.models.state_validator])),
                ('zip_code', models.CharField(max_length=5, validators=[hrm_api.models.zip_code_validator])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('staff', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
