# Generated by Django 3.0.8 on 2020-07-18 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_api', '0005_auto_20200706_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
    ]
