# Generated by Django 2.0 on 2020-08-10 04:52

from django.db import migrations, models
import hrm_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_api', '0007_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=25, validators=[hrm_api.models.gender_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=25, validators=[hrm_api.models.phone_number_validator]),
        ),
    ]
