# Generated by Django 3.0.7 on 2020-07-06 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrm_api', '0002_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
